spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness-recommendations
      database: fitness-recommendations
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: 172.20.32.1
    prefer-ip-address: true

server:
  port: 8083

rabbitmq:
  exchange:
    name: fitness-exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: {GEMINI_API_URL}
    key: {GEMINI_API_KEY}
